# FROM electronuserland/builder:20-wine AS base
# RUN apt-get update
# RUN apt-get install 
# RUN apt-get install -y ca-certificates curl

# RUN npm i -g pnpm


FROM electronuserland/builder:22-wine AS base

# 更新并安装必要工具和 canvas 依赖
RUN apt-get update && \
    apt-get install -y \
        ca-certificates \
        curl \
        bash \          
        git \
        build-essential \
        libcairo2-dev \
        libpango1.0-dev \
        libjpeg-dev \
        libgif-dev \
        librsvg2-dev \
        pkg-config \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 全局安装 pnpm
RUN npm config set registry https://mirrors.cloud.tencent.com/npm/
RUN npm install -g pnpm

# 设置默认 shell 为 bash
SHELL ["/bin/bash", "-c"]

# 可选：验证 bash 安装
RUN which bash || echo "bash not found!"
