packages:
  - apps/*
  - packages/*
  - pages/*
  - libraries/*
  - dev-tools/*
  - demo/*

ignoredBuiltDependencies:
  - core-js
  - esbuild
  - fsevents
  - highlight.js

onlyBuiltDependencies:
  - puppeteer
  - v-code-diff
  - electron
  - '@vue-office/excel'
