// style json
export const marginData = {
  key: 111550,
  type: 'card',
  category: 'container',
  icon: 'card',
  widgetList: [
    {
      key: 11400,
      type: 'number',
      icon: 'number-field',
      formItemFlag: true,
      options: {
        name: 'leftMargin',
        label: 'case.leftMargin',
        labelAlign: '',
        defaultValue: 10,
        placeholder: '',
        columnWidth: '200px',
        size: '',
        labelWidth: null,
        labelHidden: false,
        disabled: false,
        hidden: false,
        required: true,
        requiredHint: '',
        validation: '',
        validationHint: '',
        customClass: '',
        labelIconClass: null,
        labelIconPosition: 'rear',
        labelTooltip: null,
        min: -100000000000,
        max: 100000000000,
        precision: 0,
        step: 1,
        controlsPosition: 'right',
        stepStrictly: false,
        onCreated: '',
        onMounted: '',
        onChange: '',
        onFocus: '',
        onBlur: '',
        onValidate: ''
      },
      id: 'number82262'
    },
    {
      key: 11400,
      type: 'number',
      icon: 'number-field',
      formItemFlag: true,
      options: {
        name: 'rightMargin',
        label: 'case.rightMargin',
        labelAlign: '',
        defaultValue: 15,
        placeholder: '',
        columnWidth: '200px',
        size: '',
        labelWidth: null,
        labelHidden: false,
        disabled: false,
        hidden: false,
        required: true,
        requiredHint: '',
        validation: '',
        validationHint: '',
        customClass: '',
        labelIconClass: null,
        labelIconPosition: 'rear',
        labelTooltip: null,
        min: -100000000000,
        max: 100000000000,
        precision: 0,
        step: 1,
        controlsPosition: 'right',
        stepStrictly: false,
        onCreated: '',
        onMounted: '',
        onChange: '',
        onFocus: '',
        onBlur: '',
        onValidate: ''
      },
      id: 'number95334'
    }
  ],
  options: {
    name: 'marginSetting',
    label: 'case.margin',
    hidden: false,
    folded: true,
    showFold: true,
    cardWidth: '100%',
    shadow: 'never',
    customClass: ''
  },
  id: 'card114645'
}
// style json
export const legendData = {
  key: 111550,
  type: 'card',
  category: 'container',
  icon: 'card',
  widgetList: [
    {
      key: 47595,
      type: 'select',
      icon: 'select-field',
      formItemFlag: true,
      options: {
        name: 'legendTop',
        label: 'case.verticalDirection',
        labelAlign: '',
        defaultValue: 'top',
        placeholder: '',
        columnWidth: '200px',
        size: '',
        labelWidth: null,
        labelHidden: false,
        disabled: false,
        hidden: false,
        clearable: true,
        filterable: true,
        allowCreate: true,
        popperClass: '',
        remote: false,
        automaticDropdown: false,
        multiple: false,
        multipleLimit: 0,
        optionItems: [
          {
            value: 'top',
            label: 'Top'
          },
          {
            value: 'bottom',
            label: 'Bottom'
          },
          {
            value: 'center',
            label: 'Center'
          }
        ],
        required: false,
        requiredHint: '',
        validation: '',
        validationHint: '',
        customClass: '',
        labelIconClass: null,
        labelIconPosition: 'rear',
        labelTooltip: null,
        onCreated: '',
        onMounted: '',
        onRemoteQuery: '',
        onChange: '',
        changeSettings: [],
        onChangeSetting: true,
        onFocus: '',
        onBlur: '',
        onValidate:
          "if(!value) callback();  //pass\nconst percentageRegex = /^\\d+(\\.\\d+)?%$/;\nconst integerRegex = /^-?\\d+$/;\nconst isNormal = ['top','bottom','center'].includes(value)\nconst isPercentage = percentageRegex.test(value)\nconst isNum = integerRegex.test(value)\nif (isNum) this.setValue(value + '%')\n\nif (!isNormal && !isNum && !isPercentage) {\n  callback(new Error('Select or enter a percentage'))  //fail\n } else {\n  callback();  //pass\n}\n  "
      },
      id: 'select71168'
    },
    {
      key: 47595,
      type: 'select',
      icon: 'select-field',
      formItemFlag: true,
      options: {
        name: 'legendLeft',
        label: 'case.horizontalDirection',
        labelAlign: '',
        defaultValue: 'center',
        placeholder: '',
        columnWidth: '200px',
        size: '',
        labelWidth: null,
        labelHidden: false,
        disabled: false,
        hidden: false,
        clearable: true,
        filterable: true,
        allowCreate: true,
        popperClass: '',
        remote: false,
        automaticDropdown: false,
        multiple: false,
        multipleLimit: 0,
        optionItems: [
          {
            value: 'left',
            label: 'Left'
          },
          {
            value: 'center',
            label: 'Center'
          },
          {
            value: 'right',
            label: 'Right'
          }
        ],
        required: false,
        requiredHint: '',
        validation: '',
        validationHint: '',
        customClass: '',
        labelIconClass: null,
        labelIconPosition: 'rear',
        labelTooltip: null,
        onCreated: '',
        onMounted: '',
        onRemoteQuery: '',
        onChange: '',
        changeSettings: [],
        onChangeSetting: true,
        onFocus: '',
        onBlur: '',
        onValidate:
          "if(!value) callback();  //pass\nconst percentageRegex = /^\\d+(\\.\\d+)?%$/;\nconst integerRegex = /^-?\\d+$/;\nconst isNormal = ['left','right','center'].includes(value)\nconst isPercentage = percentageRegex.test(value)\nconst isNum = integerRegex.test(value)\nif (isNum) this.setValue(value + '%')\n\nif (!isNormal && !isNum && !isPercentage) {\n  callback(new Error('Select or enter a percentage'))  //fail\n } else {\n  callback();  //pass\n}\n  "
      },
      id: 'select41275'
    },
    {
      key: 104024,
      type: 'input',
      icon: 'text-field',
      formItemFlag: true,
      options: {
        name: 'legendGap',
        label: 'case.legendGap',
        labelAlign: '',
        type: 'text',
        defaultValue: '3',
        placeholder: '',
        columnWidth: '200px',
        size: '',
        labelWidth: null,
        labelHidden: false,
        readonly: false,
        disabled: false,
        hidden: false,
        clearable: true,
        showPassword: false,
        required: false,
        requiredHint: '',
        validation: 'number',
        validationHint: '',
        customClass: '',
        labelIconClass: null,
        labelIconPosition: 'rear',
        labelTooltip: null,
        minLength: null,
        maxLength: null,
        showWordLimit: false,
        prefixIcon: '',
        suffixIcon: '',
        appendButton: true,
        appendButtonText: 'px',
        prependText: '',
        appendButtonDisabled: false,
        buttonIcon: '',
        onCreated: '',
        onMounted: '',
        onInput: '',
        onChange: '',
        changeSettings: [],
        onChangeSetting: true,
        onFocus: '',
        onBlur: '',
        onEnter: '',
        onValidate: '',
        onAppendButtonClick: ''
      },
      id: 'input45653'
    }
  ],
  options: {
    name: 'showLegend',
    label: 'case.styleLegend',
    hidden: false,
    folded: true,
    showFold: true,
    cardWidth: '100%',
    shadow: 'never',
    customClass: '',
    showDisplayButton: true
  },
  id: 'card58680'
}
// setup json
export const filterArrayData = {
  key: 96243,
  type: 'sub-form',
  category: 'container',
  icon: 'sub-form',
  widgetList: [
    {
      key: 64445,
      type: 'select',
      icon: 'select-field',
      formItemFlag: true,
      options: {
        name: 'filterKey',
        label: 'case.filterKey',
        labelAlign: '',
        defaultValue: '',
        placeholder: '',
        columnWidth: '120px',
        size: '',
        labelWidth: null,
        labelHidden: false,
        disabled: false,
        hidden: false,
        clearable: true,
        filterable: true,
        allowCreate: false,
        popperClass: '',
        remote: false,
        automaticDropdown: false,
        multiple: false,
        multipleLimit: 0,
        optionItems: [],
        required: false,
        requiredHint: '',
        validation: '',
        validationHint: '',
        customClass: '',
        labelIconClass: null,
        labelIconPosition: 'rear',
        labelTooltip: null,
        onCreated: '',
        onMounted: '',
        onRemoteQuery: '',
        onChange:
          "const _this = this\nconst filterKey = 'masterTableColumn'\nasync function getList() {\n  try {\n    const data = await $api.post('/dms/master-tables/record/page/nonPermission',{where:{key: 'case_status', }, name: 'basic', }).then(res => res.data.data)\n    return data.reduce((prev, item) => {\n      if(!item.name || !item.name || prev.find(p => p.value === item.name)) return prev \n      const resultItem = {\n        value: item.name,\n        label: item.name || '' ,\n        order_num: item.order_num\n      }\n      if(filterKey === 'user') resultItem.disabled = item.status === 'A' ? false : true \n      else if(filterKey === 'masterTableColumn') resultItem.disabled = !item.status\n      prev.push(resultItem) \n      return prev\n    }, []).sort((a,b)=> (a.order_num - b.order_num ))\n  } catch (e) { return [] }\n}\nasync function init() {\n  if(!value) return\n  const filterValueRef = _this.getWidgetRef(`filterValue@row${rowId}`)\n  if(value.includes('Case_Status')) {\n    const options = await getList()\n    filterValueRef.loadOptions(options)\n  } else {\n    filterValueRef.loadOptions([])\n  }\n}\n\ninit()\n",
        changeSettings: [],
        onChangeSetting: true,
        onFocus: '',
        onBlur: '',
        onValidate: ''
      },
      id: 'select80351'
    },
    {
      key: 98577,
      type: 'async-select',
      icon: 'async-select-widget',
      formItemFlag: true,
      options: {
        name: 'filterValue',
        label: 'case.filterValue',
        labelAlign: '',
        defaultValue: [],
        placeholder: '',
        columnWidth: '120px',
        size: '',
        labelWidth: null,
        labelHidden: false,
        disabled: false,
        hidden: false,
        clearable: true,
        filterable: true,
        allowCreate: true,
        remote: false,
        automaticDropdown: false,
        multiple: true,
        multipleLimit: 0,
        optionItems: [],
        selectSetting: {
          api: 'masterTableColumn',
          method: 'get',
          params: {
            where: [
              {
                value: 'case_status',
                key: 'key'
              }
            ],
            name: 'basic'
          },
          valueKey: 'name',
          labelKey: 'name'
        },
        changeSettings: [],
        required: true,
        requiredHint: '',
        validation: '',
        validationHint: '',
        customClass: '',
        labelIconClass: null,
        labelIconPosition: 'rear',
        labelTooltip: null,
        onCreatedSetting: 'async-select',
        onChangeSetting: true,
        onCreated: '',
        onCreatedPlus: '',
        onMounted: '',
        onRemoteQuery: '',
        onChange: '',
        onChangePlus: '',
        onFocus: '',
        onBlur: '',
        onValidate: ''
      },
      id: 'asyncselect50846'
    }
  ],
  options: {
    name: 'filterList',
    showBlankRow: true,
    showRowNumber: false,
    label: 'filterList',
    labelAlign: 'label-left-align',
    hidden: false,
    disabled: false,
    maxLength: null,
    customClass: ['form-no-insert'],
    onSubFormRowAdd:
      "const _this = this\n\nsetTimeout(function() {\n  try {\n    const relativeRef = _this.getWidgetRef('fields')\n    const fields_str = relativeRef.getValue()\n    const options = JSON.parse(fields_str)\n    const filterValueRef = _this.getWidgetRef(`filterKey@row${newRowId}`)\n    filterValueRef.loadOptions(options)\n  } catch (e) {\n    console.error(e)\n  }\n}, 10)",
    onSubFormRowInsert: '',
    onSubFormRowDelete: '',
    onSubFormRowChange: ''
  },
  id: 'subform97224'
}
